server:
  port: 4000
minio:
  url: http://47.98.59.133:9000
  accessKey: minioadmin
  secretKey: minioadmin
# maxFileSize 单个数据大小
spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      # maxRequestSize 是总数据大小
      maxRequestSize: 100MB